### ISSUE TITLE
Mount/Move images to assets

### ISSUE THREAD

**Issue by nicolemah99** [acep-uaf/the-arctic-program#126]
Consider doing something like this (from `aedg-hugo`). This WILL definitely break links. Be sure to check everything.

```toml
[module]
  [module.hugoVersion]
    extended = true
    min = "0.99.1"
    max = ""
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"
```
